// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/AndreasVikke-School/CPH-Bussiness-SI-Exam/applications/services/postgres/ent/loan"
	"github.com/AndreasVikke-School/CPH-Bussiness-SI-Exam/applications/services/postgres/ent/user"
)

// Loan is the model entity for the Loan schema.
type Loan struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EntityId holds the value of the "entityId" field.
	EntityId int64 `json:"entityId,omitempty"`
	// Status holds the value of the "status" field.
	Status loan.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoanQuery when eager-loading is set.
	Edges      LoanEdges `json:"edges"`
	user_loans *int
}

// LoanEdges holds the relations/edges for other nodes in the graph.
type LoanEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoanEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Loan) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case loan.FieldID, loan.FieldEntityId:
			values[i] = new(sql.NullInt64)
		case loan.FieldStatus:
			values[i] = new(sql.NullString)
		case loan.ForeignKeys[0]: // user_loans
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Loan", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Loan fields.
func (l *Loan) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case loan.FieldEntityId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entityId", values[i])
			} else if value.Valid {
				l.EntityId = value.Int64
			}
		case loan.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				l.Status = loan.Status(value.String)
			}
		case loan.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_loans", value)
			} else if value.Valid {
				l.user_loans = new(int)
				*l.user_loans = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Loan entity.
func (l *Loan) QueryUser() *UserQuery {
	return (&LoanClient{config: l.config}).QueryUser(l)
}

// Update returns a builder for updating this Loan.
// Note that you need to call Loan.Unwrap() before calling this method if this Loan
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Loan) Update() *LoanUpdateOne {
	return (&LoanClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Loan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Loan) Unwrap() *Loan {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Loan is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Loan) String() string {
	var builder strings.Builder
	builder.WriteString("Loan(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", entityId=")
	builder.WriteString(fmt.Sprintf("%v", l.EntityId))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", l.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Loans is a parsable slice of Loan.
type Loans []*Loan

func (l Loans) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
