# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import loan_pb2 as loan__pb2


class LoanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLoan = channel.unary_unary(
                '/rpc.LoanService/GetLoan',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
                response_deserializer=loan__pb2.Loan.FromString,
                )
        self.GetAllLoans = channel.unary_unary(
                '/rpc.LoanService/GetAllLoans',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loan__pb2.LoanList.FromString,
                )
        self.GetAllLoansByUser = channel.unary_unary(
                '/rpc.LoanService/GetAllLoansByUser',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loan__pb2.LoanList.FromString,
                )
        self.CreateLoan = channel.unary_unary(
                '/rpc.LoanService/CreateLoan',
                request_serializer=loan__pb2.Loan.SerializeToString,
                response_deserializer=loan__pb2.Loan.FromString,
                )


class LoanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllLoans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllLoansByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoan,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
                    response_serializer=loan__pb2.Loan.SerializeToString,
            ),
            'GetAllLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLoans,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loan__pb2.LoanList.SerializeToString,
            ),
            'GetAllLoansByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLoansByUser,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loan__pb2.LoanList.SerializeToString,
            ),
            'CreateLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLoan,
                    request_deserializer=loan__pb2.Loan.FromString,
                    response_serializer=loan__pb2.Loan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.LoanService/GetLoan',
            google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
            loan__pb2.Loan.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.LoanService/GetAllLoans',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loan__pb2.LoanList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllLoansByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.LoanService/GetAllLoansByUser',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loan__pb2.LoanList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.LoanService/CreateLoan',
            loan__pb2.Loan.SerializeToString,
            loan__pb2.Loan.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
