# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loan.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=b'Z\004/rpc\252\002\006Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nloan.proto\x12\x03rpc\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"Q\n\x04Loan\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x10\n\x08\x65ntityId\x18\x03 \x01(\x03\x12\x1b\n\x06status\x18\x04 \x01(\x0e\x32\x0b.rpc.Status\"$\n\x08LoanList\x12\x18\n\x05loans\x18\x01 \x03(\x0b\x32\t.rpc.Loan*;\n\x06Status\x12\x0c\n\x08RESERVED\x10\x00\x12\n\n\x06PICKED\x10\x01\x12\n\n\x06PACKED\x10\x02\x12\x0b\n\x07SHIPPED\x10\x03\x32\xd6\x01\n\x0bLoanService\x12\x31\n\x07GetLoan\x12\x1b.google.protobuf.Int64Value\x1a\t.rpc.Loan\x12\x34\n\x0bGetAllLoans\x12\x16.google.protobuf.Empty\x1a\r.rpc.LoanList\x12:\n\x11GetAllLoansByUser\x12\x16.google.protobuf.Empty\x1a\r.rpc.LoanList\x12\"\n\nCreateLoan\x12\t.rpc.Loan\x1a\t.rpc.LoanB\x0fZ\x04/rpc\xaa\x02\x06Protosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='rpc.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PICKED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PACKED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHIPPED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=201,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
RESERVED = 0
PICKED = 1
PACKED = 2
SHIPPED = 3



_LOAN = _descriptor.Descriptor(
  name='Loan',
  full_name='rpc.Loan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rpc.Loan.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='rpc.Loan.userId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entityId', full_name='rpc.Loan.entityId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='rpc.Loan.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=161,
)


_LOANLIST = _descriptor.Descriptor(
  name='LoanList',
  full_name='rpc.LoanList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loans', full_name='rpc.LoanList.loans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=199,
)

_LOAN.fields_by_name['status'].enum_type = _STATUS
_LOANLIST.fields_by_name['loans'].message_type = _LOAN
DESCRIPTOR.message_types_by_name['Loan'] = _LOAN
DESCRIPTOR.message_types_by_name['LoanList'] = _LOANLIST
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Loan = _reflection.GeneratedProtocolMessageType('Loan', (_message.Message,), {
  'DESCRIPTOR' : _LOAN,
  '__module__' : 'loan_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Loan)
  })
_sym_db.RegisterMessage(Loan)

LoanList = _reflection.GeneratedProtocolMessageType('LoanList', (_message.Message,), {
  'DESCRIPTOR' : _LOANLIST,
  '__module__' : 'loan_pb2'
  # @@protoc_insertion_point(class_scope:rpc.LoanList)
  })
_sym_db.RegisterMessage(LoanList)


DESCRIPTOR._options = None

_LOANSERVICE = _descriptor.ServiceDescriptor(
  name='LoanService',
  full_name='rpc.LoanService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=263,
  serialized_end=477,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLoan',
    full_name='rpc.LoanService.GetLoan',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._INT64VALUE,
    output_type=_LOAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllLoans',
    full_name='rpc.LoanService.GetAllLoans',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LOANLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllLoansByUser',
    full_name='rpc.LoanService.GetAllLoansByUser',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_LOANLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateLoan',
    full_name='rpc.LoanService.CreateLoan',
    index=3,
    containing_service=None,
    input_type=_LOAN,
    output_type=_LOAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOANSERVICE)

DESCRIPTOR.services_by_name['LoanService'] = _LOANSERVICE

# @@protoc_insertion_point(module_scope)
