// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LoansColumns holds the columns for the "loans" table.
	LoansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "entity_id", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"RESERVED", "PICKED", "PACKED", "SHIPPED"}},
		{Name: "user_loans", Type: field.TypeInt, Nullable: true},
	}
	// LoansTable holds the schema information for the "loans" table.
	LoansTable = &schema.Table{
		Name:       "loans",
		Columns:    LoansColumns,
		PrimaryKey: []*schema.Column{LoansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "loans_users_loans",
				Columns:    []*schema.Column{LoansColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "age", Type: field.TypeInt64},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoansTable,
		UsersTable,
	}
)

func init() {
	LoansTable.ForeignKeys[0].RefTable = UsersTable
}
