// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	EntityId             int64    `protobuf:"varint,3,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Unix                 int64    `protobuf:"varint,4,opt,name=unix,proto3" json:"unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Log) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Log) GetEntityId() int64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *Log) GetUnix() int64 {
	if m != nil {
		return m.Unix
	}
	return 0
}

type LogRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LogList struct {
	Logs                 []*Log   `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogList) Reset()         { *m = LogList{} }
func (m *LogList) String() string { return proto.CompactTextString(m) }
func (*LogList) ProtoMessage()    {}
func (*LogList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *LogList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogList.Unmarshal(m, b)
}
func (m *LogList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogList.Marshal(b, m, deterministic)
}
func (m *LogList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogList.Merge(m, src)
}
func (m *LogList) XXX_Size() int {
	return xxx_messageInfo_LogList.Size(m)
}
func (m *LogList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogList.DiscardUnknown(m)
}

var xxx_messageInfo_LogList proto.InternalMessageInfo

func (m *LogList) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "rpc.Log")
	proto.RegisterType((*LogRequest)(nil), "rpc.LogRequest")
	proto.RegisterType((*LogList)(nil), "rpc.LogList")
}

func init() {
	proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886)
}

var fileDescriptor_a153da538f858886 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xd9, 0x3f, 0xd4, 0x76, 0x2c, 0x56, 0x72, 0x90, 0x65, 0x15, 0x2d, 0xbd, 0x58, 0x2f,
	0x29, 0xd4, 0xe2, 0xcd, 0x83, 0xf5, 0x50, 0x16, 0x72, 0x90, 0x8a, 0x1e, 0x04, 0x0f, 0xdb, 0xdd,
	0x31, 0x04, 0xc2, 0x26, 0x26, 0x59, 0xb5, 0x4f, 0xe2, 0x3b, 0xf8, 0x94, 0xb2, 0xd9, 0x76, 0xbd,
	0x7a, 0xcb, 0x7c, 0xf9, 0xcd, 0x37, 0xc3, 0xc0, 0x40, 0x2a, 0x4e, 0xb5, 0x51, 0x4e, 0x91, 0xc8,
	0xe8, 0x22, 0x3d, 0xe7, 0x4a, 0x71, 0x89, 0x33, 0x8f, 0x36, 0xf5, 0xdb, 0xec, 0xd3, 0xe4, 0x5a,
	0xa3, 0xb1, 0x6d, 0x68, 0xf2, 0x0a, 0x11, 0x53, 0x9c, 0x1c, 0x41, 0x28, 0xca, 0x24, 0x18, 0x07,
	0xd3, 0x68, 0x1d, 0x8a, 0x92, 0x9c, 0x40, 0xaf, 0xb6, 0x68, 0xb2, 0x32, 0x09, 0x3d, 0xdb, 0x55,
	0x24, 0x85, 0x3e, 0x56, 0x4e, 0xb8, 0x6d, 0x56, 0x26, 0x91, 0xff, 0xe9, 0x6a, 0x42, 0x20, 0xae,
	0x2b, 0xf1, 0x95, 0xc4, 0x9e, 0xfb, 0xf7, 0x64, 0x01, 0xc0, 0x14, 0x5f, 0xe3, 0x7b, 0x8d, 0xd6,
	0xfd, 0x77, 0xca, 0xe4, 0x12, 0x0e, 0x98, 0xe2, 0x4c, 0x58, 0x47, 0xce, 0x20, 0x96, 0x8a, 0xdb,
	0x24, 0x18, 0x47, 0xd3, 0xc3, 0x79, 0x9f, 0x1a, 0x5d, 0xd0, 0xc6, 0xe8, 0xe9, 0xfc, 0x3b, 0xf0,
	0xfe, 0x47, 0x34, 0x1f, 0xa2, 0x40, 0x72, 0x05, 0xc3, 0x15, 0x3a, 0xa6, 0xf8, 0x72, 0xfb, 0x64,
	0xd1, 0x90, 0x51, 0x17, 0x6f, 0x17, 0x48, 0xbb, 0x7e, 0x72, 0x0b, 0xc7, 0x2b, 0x74, 0x77, 0x52,
	0x32, 0xc5, 0xed, 0x2e, 0x7e, 0x4a, 0xdb, 0x63, 0xd1, 0xfd, 0xb1, 0x68, 0x56, 0xb9, 0x9b, 0xc5,
	0x73, 0x2e, 0x6b, 0x4c, 0x87, 0xfb, 0x56, 0xbf, 0xd6, 0x05, 0x0c, 0xee, 0x0d, 0xe6, 0x0e, 0x1b,
	0x57, 0x67, 0xfd, 0xf3, 0x2f, 0x47, 0x2f, 0xf1, 0xcc, 0xe8, 0xe2, 0x27, 0xec, 0x3d, 0x34, 0x32,
	0xbb, 0xe9, 0x79, 0xe9, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xed, 0x27, 0xce, 0xa1,
	0x01, 0x00, 0x00,
}
