name: "main_images_build"

on:
  push:
    branches:
      - main

jobs:
  call-workflow-build-push-api-image:
    name: Build and Push api service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: api_service
      image_path: "applications/services/api"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-postgres-image:
    name: Build and Push postgres service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: postgres_service
      image_path: "applications/services/postgres"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-redis-image:
    name: Build and Push redis service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: redis_service
      image_path: "applications/services/redis"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
  
  call-workflow-build-push-neo4j-image:
    name: Build and Push neo4j service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: neo4j_service
      image_path: "applications/services/neo4j"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-rabbitmq-image: 
    name: Build and Push rabbitmq service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: rabbitmq_service
      image_path: "applications/services/rabbitmq"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

  call-workflow-build-push-kafka-image: 
    name: Build and Push kafka service Docker Image
    uses: andreasvikke-school/CPH-Business-SI-Exam/.github/workflows/template_build_push.yaml@main
    with:
      image_name: kafka_service
      image_path: "applications/services/kafka"
    secrets:
      ghcr_token: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}